config/routes.rb
Rails.application.routes.draw do
  resources :dashboard

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	session[:oauth] = Koala::Facebook::OAuth.new(APP_ID, APP_SECRET, SITE_URL + '/dashboard/show')
  	@auth_url = session[:oauth].url_for_oauth_code(permissions: [:read_stream, :email])
  	puts session.to_s + "<<< session"
  	respond_to do |format|
  		format.html {  }
  	end
  end

  def show
  	session[:oauth] = Koala::Facebook::OAuth.new(APP_ID, APP_SECRET, SITE_URL + '/dashboard/show')
  	if params[:code]
  		session[:access_token] = session[:oauth].get_access_token(params[:code])
  	end
  	@api = Koala::Facebook::API.new(session[:access_token])
  	
  	begin
  		@profile = @api.get_object("me")
      # Because of facebook permissions, you are only able to view friends who are also using the same app
  		@friends = @api.get_object("me/friends?fields=id,name,picture")
  	end
  	respond_to do |format|
  		format.html {  }
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<p>Check your list of mutual Facebook Friends!</p>

<%= link_to 'Login to Facebook', @auth_url, class: "button" %> 

app/views/dashboard/show.html.erb
<h1>Your Facebook Information</h1>
<%= link_to 'Logout', dashboard_index_path, class: 'logout' %>
<img src='https://graph.facebook.com/<%= @profile["id"] %>/picture' alt='picture'>
<div class="profile_info"> 
   <h4>Name: <%= @profile["name"] %></h2>
   <h4>Email Address: <%= @profile["email"] %></h4>
</div>
<h3>Facebook Friends Who Also Use This App</h3>
<% @friends.each do |friend| %>
   <div class="contact_box">
   	<h4><%= friend["name"] %></h4>
      <%= image_tag friend["picture"]["data"]["url"] %>
   </div>
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookLogin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>